global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'vortex_api'
    scrape_interval: 5s
    static_configs:
      - targets: ['vortex_api:8000']
    metrics_path: '/metrics'

  - job_name: 'vortex_qdrant'
    scrape_interval: 5s
    static_configs:
      - targets: ['vortex_qdrant:6333']
    metrics_path: '/metrics'
    authorization:
      type: Bearer
      credentials: 'vortex-secret-admin-key'

  - job_name: 'vortex_redis'
    scrape_interval: 5s
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'vortex_celery'
    scrape_interval: 5s
    static_configs:
      - targets: ['celery-exporter:9808']
